runtime: nodejs20
env: flexible
threadsafe: true
automatic_scaling:
  min_num_instances: 4
  max_num_instances: 100
  cpu_utilization:
    target_utilization: 0.8
liveness_check:
  path: "/_ah/health"
readiness_check:
  path: "/_ah/health"
