steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - ${_DEPLOY_VERSION}
      - --runtime=${_RUNTIME}
      - --set-env-vars
      - COMMIT_SHA=$COMMIT_SHA
